name: DNF-Repo For GitHub
description: 'Update a dnf-compatible repository from GitHub release'
inputs:
  # Descriptions for these input variables can be found in `README.adoc`
  from_repository:
    required: true
    type: string
  from_version:
    required: true
    type: string
  files:
    required: true
    type: string
  to_repository:
    required: true
    type: string
  to_branch:
    default: 'gh-pages'
    type: string
  to_path:
    default: 'central'
    type: string
  max_attempts:
    default: 5
    type: string
  deploy_key:
    required: true
    type: string
  gpg_public_key:
    required: true
    type: string
  repo_baseurl:
    type: string
  repo_name:
    default: 'teragrep-central-releases'
    type: string
runs:
  using: composite
  steps:
    - name: Add component to main repository
      run: |
        if [ "${{ inputs.repo_baseurl }}" == "" ]; then
          export REPO_BASEURL="https://raw.githubusercontent.com/${{ inputs.to_repository }}/refs/heads/${{ inputs.to_branch }}/${{ inputs.to_path }}";
          echo "Custom baseurl was not set, using '${REPO_BASEURL}'";
        else
          export REPO_BASEURL="${{ inputs.repo_baseurl }}";
          echo "Detected baseurl, set to '${REPO_BASEURL}'";
        fi;
        export DFG_01_TMPDIR="$(mktemp --directory --tmpdir=${{ runner.temp }})";
        mkdir --parents "${DFG_01_TMPDIR}/rpm/${{ inputs.from_version }}" "${DFG_01_TMPDIR}/component-repo" "${DFG_01_TMPDIR}/merged-repo";
        for file in ${{ inputs.files }}; do ln --verbose "${{ github.workspace }}/${file}" "${DFG_01_TMPDIR}/rpm/${{ inputs.from_version }}/$(basename ${file})"; done;
        sudo apt-get update;
        sudo apt-get --yes install createrepo-c;
        createrepo_c --verbose --no-database --baseurl=https://www.github.com --location-prefix="https://github.com/${{ inputs.from_repository }}/releases/download/" --outputdir="${DFG_01_TMPDIR}/component-repo" "${DFG_01_TMPDIR}/rpm";
        git config --global user.email "${{ github.actor }}@users.noreply.github.com";
        git config --global user.name "${{ github.actor }}";
        echo "${GH_SSH_KEY}" > "${DFG_01_TMPDIR}/ssh.key";
        export GIT_SSH_COMMAND="ssh -i ${DFG_01_TMPDIR}/ssh.key";
        chmod 400 "${DFG_01_TMPDIR}/ssh.key";
        export attempt=0;
        while true; do
          export attempt="$((attempt+1))";
          echo "Attempt ${attempt}/${{ inputs.max_attempts }}";
          [ -d upstream/ ] && rm --recursive --force upstream;
          rm --recursive --force "${DFG_01_TMPDIR}/merged-repo/*";
          bash -c '
            set -e;
            git clone --branch "${{ inputs.to_branch }}" -- "git@github.com:${{ inputs.to_repository }}.git" upstream;
            mergerepo_c --verbose --simple-md-filenames --all --no-database --repo="upstream/${{ inputs.to_path }}/releases" --repo="${DFG_01_TMPDIR}/component-repo" --outputdir "${DFG_01_TMPDIR}/merged-repo";
            rm --recursive --force "upstream/${{ inputs.to_path }}/releases/repodata/";
            mv --verbose "${DFG_01_TMPDIR}/merged-repo/repodata/" "upstream/${{ inputs.to_path }}/releases/repodata";
            echo -e "[${{ inputs.repo_name }}]\nname=${{ inputs.repo_name }}\nbaseurl=${REPO_BASEURL}/releases\ngpgcheck=1\ngpgkey=${REPO_BASEURL}/releases/${{ inputs.repo_name }}-gpg-key.pub\nenabled=1" > "upstream/${{ inputs.to_path }}/releases/${{ inputs.repo_name }}.repo";
            echo "${{ inputs.gpg_public_key }}" > "upstream/${{ inputs.to_path }}/releases/${{ inputs.repo_name }}-gpg-key.pub";
            cd "upstream/${{ inputs.to_path }}";
            git add .;
            git commit --message "Adds ${{ inputs.from_repository }} version ${{ inputs.from_version }}";
            git push;
          ' && break;
          if [[ "${attempt}" -ge "${{ inputs.max_attempts }}" ]]; then
            echo "Max attempts encountered, failing";
            exit 1;
          fi;
          sleep 5;
        done;
        rm --recursive --force "${DFG_01_TMPDIR}/";
        echo "Deployed successfully to repository ${{ inputs.to_repository }}!";
      shell: bash
      env:
        GH_SSH_KEY: "${{ inputs.deploy_key }}"
