= DFG_01 DNF-Repo For GitHub

A simple to use GitHub Action that updates a dnf-compatible repository from `.rpm` files sourced from provided GitHub release.

== Features

- The repository data points directly to `.rpm` files so no re-hosting of binaries is necessary.

- Supports any release from any GitHub repository as long as it has `.rpm` files present.

- Supports configurable max retries to avoid merge issues and infinite loops.

- Creates a ready to use `.repo` file.

== Requirements

You need to have a https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens[Personal Access Token] that has `read` permission to the `from_repository` and `write` permission to `to_repository`.

== Limitations

- Supports only GitHub repositories.

== Usage

Add a `uses: teragrep/dfg_01@main` https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepsuses[step] to your workflow.

Examples uses a secret called `PAT_TOKEN` that contains the token. **DO NOT** hardcode the token at any point.

.Minimum configuration with only required arguments
[source,yaml]
----
- name: Update from release
  uses: teragrep/dfg_01@main
  with:
    from_repository: teragrep/example-repository
    from_version: 1.0.0
    to_repository: teragrep/central-repository
    token: ${{ secrets.PAT_TOKEN }}
----

.Full configuration with optional arguments
[source,yaml]
----
- name: Update from release
  uses: teragrep/dfg_01@main
  with:
    from_repository: teragrep/example-repository
    from_version: 1.0.0
    to_repository: teragrep/central-repository
    token: ${{ secrets.PAT_TOKEN }}
    to_branch: arbitrary-git-branch
    to_path: arbitrary-base-path
    max_attempts: 1
----

== Documentation

These are required arguments to be used in `with:` block.

|===
|Required input argument|Description|Example value

|`from_repository`
|The source GitHub repository for the release. In `user/repository` format.
|`teragrep/release-repo`

|`from_version`
|The *exact* release version.
|`1.0.0`

|`to_repository`
|The target GitHub repository where the repodata is deployed to. In `user/repository` format.
|`teragrep/dnf-repo`

|`token`
|The Personal Access Token to be used with downloading and committing.
|`github_path_SOMEEXAMPLEKEY`
|===

These are optional arguments to be used in `with:` block.
|===
|Optional input argument|Description|Default value

|`to_branch`
|The branch where repository files are commited to.
|`gh-pages`

|`to_path`
|The path where repository files are commited to. No trailing slash required.
|`central`

|`max_attempts`
|How times should committing should be attempted.
|`5`
|===
